
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Tue Apr 21 04:23:11 CDT 2015
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 5;
  static final int rw_WHILE = 44;
  static final int rw_BOOL = 18;
  static final int LBRACKET = 27;
  static final int INCREMENT = 26;
  static final int rw_IF = 16;
  static final int SLASH = 45;
  static final int rw_CONTINUE = 36;
  static final int rw_FALSE = 38;
  static final int LPAREN = 7;
  static final int SEMI = 6;
  static final int rw_PRINT = 39;
  static final int rw_TRUE = 42;
  static final int MINUS = 13;
  static final int DECREMENT = 23;
  static final int RPAREN = 8;
  static final int NOT = 30;
  static final int rw_VOID = 43;
  static final int INTLIT = 3;
  static final int LT = 29;
  static final int rw_CONST = 35;
  static final int COMMA = 21;
  static final int rw_ELSE = 37;
  static final int GEQ = 24;
  static final int PLUS = 12;
  static final int rw_READ = 40;
  static final int rw_INT = 17;
  static final int EOF = 0;
  static final int RBRACKET = 31;
  static final int error = 1;
  static final int COR = 22;
  static final int rw_CLASS = 34;
  static final int rw_RETURN = 41;
  static final int EQ = 14;
  static final int ASG = 9;
  static final int TIMES = 46;
  static final int CHARLIT = 4;
  static final int COLON = 20;
  static final int LBRACE = 10;
  static final int rw_CHAR = 33;
  static final int RBRACE = 11;
  static final int CAND = 19;
  static final int LEQ = 28;
  static final int rw_BREAK = 32;
  static final int GT = 25;
  static final int NOTEQ = 15;
  static final int IDENTIFIER = 2;
}

